### ISSUE TITLE
[Suggestion] More than 10k points given to top player on completing bonus

### ISSUE THREAD

**Issue by g2dgaming** [surftimer/Surftimer-olokos#67] opened 2020-04-26 20:09 UTC
My Problem: Top players on my server are getting more than 10k points on completing the bonus.
What I suggest: a convar to control or disable max points or point system for bonus.
ALSO(SCREENSHOT): The Total Pts. on the server are capped to 32767 in profile menu, is there a way to change it? The total sum of the points awarded is more than the capped value shown in the profile menu, please have a look at the screenshot to understand the same
![20200427013614_1](https://user-images.githubusercontent.com/62881246/80318457-e37ddc80-8827-11ea-9e24-888263b73030.jpg)

**Comment by 13ace37** [comment] 2020-04-27 17:16
Something is wrong with your database I guess. Didn't know cs:go released 50 years ago 😂 .

**Comment by dPexxIAM** [comment] 2020-04-29 14:35
I think the reason for that strange timestamp is due to him migrating from a previous fork and the default value for the column being set to Unix Epoch. IE the start date of Unix timestamps. 

As for bonus points, you can see how they are awarded here: https://github.com/olokos/Surftimer-olokos/blob/4ae732c5ce6d5f4e65aea66ff7a24449a933b20f/addons/sourcemod/scripting/surftimer/sql.sp#L745

250 points for a rank 1. 71 bonuses completed meaning he could potentially have 17,750 points for completing bonuses. 

The points which are being displayed to you for bonuses I think are his WR points for bonuses + his others points (meaning any bonus he doesn't have rank 1 on)

I could be wrong about this. Someone else should double-check.

**Comment by sneak-it** [comment] 2020-04-29 15:28
Just a follow up to @dPexxIAM comment, those are total bonus points which seems totally right. If they were getting 10k+ points PER bonus, this would be an issue.

I plan on adding a cvar in the future as a new feature to regulate a bonus point multiplier so server owners can tweak them to their liking.

**Comment by dPexxIAM** [comment] 2020-05-21 15:11
I'm closing this issue because it's a feature and not a bug.

@sneak-it May want to open another issue about the cvar he spoke about adding, though!

**Closed by dPexxIAM** 2020-05-21 15:11 UTC
Labels: awaiting response, bug, template-unused, trivial
