### ISSUE TITLE
[BUG] After doing !spec cant go back to either side

### ISSUE THREAD

**Issue by royysz** [surftimer/Surftimer-olokos#150] opened 2020-05-22 23:36 UTC
**Describe the bug**
After going to spectate you cant go back in either side, you have to reconnect to the server to go back and play the map

**Expected behavior**
you should just go on the side you chose after going to spec
**Screenshots**

**Plugin List**
List of all your current sourcemod plugins, if applicable to the issue.
only surftimer
**Timer Version**
The major timer version. If you are using an self-compiled version off release schedule, specify the commit.
version from latest release.

**Additional context**

**Comment by Bara** [comment] 2020-05-22 23:39
And when you stop the round to start a new one?

**Comment by FR33K1LL** [comment] 2020-05-22 23:47
Duplicate of #83 ?

**Comment by Bara** [comment] 2020-05-22 23:50
^

**Closed by Bara** 2020-05-22 23:50 UTC
Labels: bug
