### ISSUE TITLE
[BUG] !ve with one person causes garbage calculations

### ISSUE THREAD

**Issue by samatazz** [surftimer/Surftimer-olokos#31] opened 2020-04-17 17:15 UTC
**Describe the bug**
Math is weird when using !ve with one person (only count tested)

**Expected behavior**
should just say 100% says a big negative number

**Screenshots**
![image](https://user-images.githubusercontent.com/29045525/79619150-60180900-810c-11ea-8130-c18255c1456c.png)

**Plugin List**
N/A

**Comment by pabes-exe** [comment] 2020-04-20 10:26
I tested this with diff player counts on an active server
It still says the -2147....% of x votes
It doesnt matter if its negative or positive

**Comment by sashajov** [comment] 2020-04-22 07:55
Mr. Olokos told me to share this here. https://pastebin.com/6uWxRxkX

**Comment by sneak-it** [comment] 2020-04-27 21:09
@sashajov Looks like this can be run independently of the timer, would you mind sending a PR to the repo with this (or host it yourself and we'll link to it)? I'd like to take VE out of the timer entirely and use this as an independent plugin or sub module.

**Comment by FR33K1LL** [comment] 2020-05-10 00:09
Ok, so I am to use sashajov's copy paste as an individual vote extend plugin to fix this bug? Just want to confirm this works with release 285. I'll also test it and report back.

**Comment by sashajov** [comment] 2020-05-12 21:42
> @sashajov Looks like this can be run independently of the timer, would you mind sending a PR to the repo with this (or host it yourself and we'll link to it)? I'd like to take VE out of the timer entirely and use this as an independent plugin or sub module.

I didn't create this. One guy exported that from ckSurf I guess and created stand-alone plugin. You can use this, Olokos can integrate if he want... :)

**Comment by Bara** [comment] 2020-05-12 22:15
I could reproduce in this a simple test case.
```sp
#include <sourcemod>

public void OnPluginStart()
{
    float percent = view_as<float>(1) / view_as<float>(1);
    PrintToServer("%d", RoundToNearest(100.0*percent));
}
```
this works fine should fix this "bug":
```sp
#include <sourcemod>

public void OnPluginStart()
{
    float percent = float(1 / 1);
    PrintToServer("%d", RoundToNearest(100.0*percent));
}
```

**Comment by FR33K1LL** [comment] 2020-05-20 00:02
is this fix merged into the latest dev?

**Comment by Bara** [comment] 2020-05-20 04:29
Just in threadedSQL.

**Comment by Kyli3Boi** [comment] 2020-05-20 10:40
I do not think this is fixed. Im using 285.95 and still have this issue

**Comment by Bara** [comment] 2020-05-20 10:45
wait... it's fixed in the dev branch and threadedSQL isn't rebased yet.

**Comment by Bara** [comment] 2020-05-22 22:33
Reopen if it still happens.

**Closed by Bara** 2020-05-22 22:33 UTC
Labels: 286, bug
