### ISSUE TITLE
[BUG] double text on chat

### ISSUE THREAD

**Issue by Caaine** [surftimer/Surftimer-olokos#93] opened 2020-05-03 16:36 UTC
**Describe the bug**
when leav the startzone on staged maps

**Screenshots**
![unknown1](https://user-images.githubusercontent.com/13827296/80919894-b4f28b00-8d6c-11ea-8d09-5b36f0c34290.png)

**Additional context**
Dev branch

**Comment by KristianP26** [comment] 2020-05-03 16:56
Thats because of Stage records and map records.

**Comment by Caaine** [comment] 2020-05-03 17:24
another duplicate message on staged maps
CP[1] and Stage 1? CP=Checkpoint?
![unknown](https://user-images.githubusercontent.com/13827296/80921000-b5daeb00-8d73-11ea-9dad-11347e6998e7.png)

**Comment by qawery-just-sad** [comment] 2020-05-03 20:27
that should have been fixed by #11

**Comment by qawery-just-sad** [comment] 2020-05-04 07:02
disregard my previous comment

**Comment by FR33K1LL** [comment] 2020-05-17 02:57
can confirm i am getting this happening on 285.95 as well

**Comment by qawery-just-sad** [comment] 2020-05-17 09:44
The thing with cp1 and stage1 has been explained by @KristianP26 as well as on discord, but i'm gonna say it here as well.
CP1 = main run, whole map.  Stage 1 = time for that stage only.
The prestrafe message displaying two times for stage1 is @LubricantJam fault (don't worry i have nothing against u i'm just saying who made the change <3)

**Comment by dPexxIAM** [comment] 2020-05-21 15:10
I'm closing this issue because this is a feature, not a bug.

**Closed by dPexxIAM** 2020-05-21 15:10 UTC
Labels: bug

**Comment by FR33K1LL** [comment] 2020-05-21 21:46
I dont think so, the bug is that when u leave the startzone it displays the first screenshot in this thread. Even if i beat the map/set a pb it will always display my wr / pb / speed aa the same values

**Comment by dPexxIAM** [comment] 2020-05-22 11:56
None of this was described to have been happening previously.

My understanding was that the bug was simply the double text when leaving start zones on stage maps.

Please feel free to open a new issue.

**Comment by FR33K1LL** [comment] 2020-05-22 11:59
My mistake dpexx, i was thinking of something else sorry.
