### ISSUE TITLE
[BUG] Hookzones exception

### ISSUE THREAD

**Issue by FR33K1LL** [surftimer/Surftimer-olokos#142] opened 2020-05-18 22:15 UTC
**Describe the bug**
[SM] Exception reported: Menu handle 3c10289 is invalid (error 1)
[SM] Blaming: SurfTimer.smx
[SM] Call stack trace:
[SM]   [0] DisplayMenu
[SM]   [1] Line 4293, surftimer/commands.sp::HookZonesMenu
[SM]   [2] Line 1601, surftimer/surfzones.sp::Handle_SelectNormalZoneType

**Expected behavior**
Display the hook zones menu when selected

**Screenshots**

**Plugin List**
List of all your current sourcemod plugins, if applicable to the issue.

**Timer Version**
dev 285.95

**Additional context**

**Comment by Kyli3Boi** [comment] 2020-05-20 06:55
Can confirm ^

**Comment by Kyli3Boi** [comment] 2020-05-20 06:58
Duplicate of #133 @FR33K1LL

**Closed** 2020-05-20 07:23 UTC
Labels: bug
