### ISSUE TITLE
[BUG] Incorrect PB Chat time - Styles

### ISSUE THREAD

**Issue by stunslave** [surftimer/Surftimer-olokos#171] opened 2020-06-02 07:32 UTC
**Describe the bug**
When completing the map/bonus in any style other than normal it always shows **You missed your PB of "time finished"** This shows your Normal PB instead of the Style that you are currently playing. _(This happens if the map is completed in style Normal)_

**_Example_**: If I'm playing HSW, it shows **-You missed your PB of** _Style Normal_ **"time finished"-**

**Additional context**
It has always been like this, since the early days when styles were first added to the timer.

**Timer Version**
285.95

**Comment by qawery-just-sad** [comment] 2020-06-02 07:34
duplicate of #154

**Closed** 2020-06-08 15:59 UTC
Labels: bug
