### ISSUE TITLE
[BUG] Results of !ve displays with max int

### ISSUE THREAD

**Issue by bali2k** [surftimer/Surftimer-olokos#151] opened 2020-05-23 01:06 UTC
**Describe the bug**
Results of !ve displays with max int

**Screenshots**
![image](https://user-images.githubusercontent.com/63168637/82718344-41c0a280-9ca2-11ea-8b30-de5d114e4cd4.png)

**Timer Version**
Master branch

**Comment by FR33K1LL** [comment] 2020-05-23 01:11
Duplicate of #31

**Closed** 2020-05-23 05:52 UTC
Labels: bug
