### ISSUE TITLE
[BUG] Prestafe Speed Mode Broken

### ISSUE THREAD

**Issue by stunslave** [surftimer/Surftimer-olokos#156] opened 2020-05-25 17:25 UTC
**Describe the bug**
Speed Mode is always set to XYZ, even when changed in options. 
Image below shows Speed Mode in options changed to XY, but the prestrafe speed is the same as what I get in XYZ. _(Hard to explain this)_

Edit: Currently the **prestrafe chat speed** does not get affected by the **Speed Mode**, in which it should. (Center Speed Display works correctly)

**Screenshots**
https://i.imgur.com/DjNYcxB.png

**Timer Version**
285.95 (latest dev)

**Comment by qawery-just-sad** [comment] 2020-05-25 18:34
duplicate of #128

**Closed** 2020-06-09 23:58 UTC
Labels: bug, duplicate
